In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])

In [8]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print (c)
print("for loop:" + str(1000*(toc-tic)) + "ms")

250051.44796165856
vectorized version:1.1630058288574219ms
250051.44796165958
for loop:752.5713443756104ms


In [14]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [15]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [16]:
percentage = 100*A/cal.reshape(1,4)
print (percentage)


[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [17]:
a = np.random.rand(5)
print(a)

[0.25414685 0.21496604 0.2625764  0.69057392 0.26094752]


In [18]:
print(a.shape)

(5,)


In [19]:
print(a.T)

[0.25414685 0.21496604 0.2625764  0.69057392 0.26094752]


In [20]:
print(np.dot(a,a.T))

0.7247333273444447


In [26]:
a = np.random.randn(5,1)
print(a)

[[-1.00394649]
 [ 1.45700028]
 [-0.14715892]
 [ 0.1374406 ]
 [-1.02878578]]


In [23]:
print(a.T)

[[0.93098583 0.37078641 0.89529026 0.66116296 0.27685364]]


In [24]:
print(a.shape)

(5, 1)


In [25]:
print(np.dot(a,a.T))

[[0.86673461 0.34519689 0.83350255 0.61553334 0.25774681]
 [0.34519689 0.13748256 0.33196146 0.24515024 0.10265357]
 [0.83350255 0.33196146 0.80154466 0.59193276 0.24786437]
 [0.61553334 0.24515024 0.59193276 0.43713646 0.18304537]
 [0.25774681 0.10265357 0.24786437 0.18304537 0.07664794]]


In [7]:
img = np.random.randn(32,32,3)
print(img.shape)
img_col = img.reshape(32*32*3,1)
print(img_col.shape)

(32, 32, 3)
(3072, 1)


In [9]:
a = np.random.randn(2,3)
b = np.random.randn(2,1)
c = a + b
print(c.shape)


(2, 3)


In [11]:
a = np.random.rand(4,3)
b = np.random.rand(3,2)
c = a*b
print(c.shape)


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [12]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [20]:
a = np.random.rand(3,4)
b = np.random.rand(4,1)
c = np.random.randn(3,4)
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

print(c.shape)
print(c)
c = a + b.T
print(c)

(3, 4)
[[1.86797518 1.48034653 0.97347494 0.10690836]
 [1.3412936  1.49189001 0.92327517 0.16663585]
 [1.87254084 1.14363878 1.57575354 0.97821894]]
[[1.86797518 1.48034653 0.97347494 0.10690836]
 [1.3412936  1.49189001 0.92327517 0.16663585]
 [1.87254084 1.14363878 1.57575354 0.97821894]]


In [21]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a * b
print(c.shape)

(3, 3)
